# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8937-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter mi8937 land riva rolex santoni tiare ulysse landtoni prada rova ulova,$(TARGET_DEVICE)),)

endif
