# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8937-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter land santoni ulysse rova tiare landtoni mi8937 ulova,$(TARGET_DEVICE)),)

endif
